/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iiR0s8X8Avd
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { TextArea } from "@/components/ui/text-area";

export function ServiceDetailsPage() {
    return (
        <div>
            <section className="py-12 md:py-20">
                <div className="container mx-auto px-6 md:px-10">
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                        <div>
                            <img
                                alt="Service"
                                className="rounded-lg object-cover w-full aspect-[3/2]"
                                height={400}
                                src="/placeholder.svg"
                                width={600}
                            />
                        </div>
                        <div className="grid gap-6">
                            <div>
                                <h1 className="text-3xl font-bold">Plumbing Services</h1>
                                <p className="text-gray-600 mt-2">Experienced plumbers for all your plumbing needs.</p>
                            </div>
                            <div className="grid gap-2">
                                <div className="flex items-center justify-between">
                                    <h2 className="text-2xl font-bold">$99 / hour</h2>
                                    <div className="flex items-center space-x-2">
                                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                                        <span className="text-gray-600">5 (200 reviews)</span>
                                    </div>
                                </div>
                                <p className="text-gray-600">
                                    Our experienced plumbers are dedicated to providing high-quality services for all your plumbing
                                    needs. From fixing leaks to installing new fixtures, we have the expertise to get the job done
                                    right.
                                </p>
                            </div>
                            <div className="grid gap-4">
                                <div className="flex items-center space-x-4">
                                    <Avatar className="w-12 h-12 border">
                                        <AvatarImage alt="John Doe" src="/placeholder-user.jpg" />
                                        <AvatarFallback>JD</AvatarFallback>
                                    </Avatar>
                                    <div>
                                        <h3 className="text-lg font-bold">John Doe</h3>
                                        <p className="text-gray-600">Plumber</p>
                                    </div>
                                </div>
                                <Button className="w-full">Book Now</Button>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <section className="bg-gray-100 py-12 md:py-20">
                <div className="container mx-auto px-6 md:px-10">
                    <h2 className="text-2xl md:text-3xl font-bold mb-8">Leave A Review</h2>
                    {/*<ReactStars
                            count={5}
                            size={24}
                            color2={'#ffd700'} />*/}
                    <div className="flex items-center mb-4">
                        {/* <Input type="text" className="grow" /> */}
                        <TextArea></TextArea>
                    </div>
                    <div className="flex justify-between">
                        <div className="flex">
                            <StarIcon className="w-5 h-5 fill-yellow-500" />
                            <StarIcon className="w-5 h-5 fill-yellow-500" />
                            <StarIcon className="w-5 h-5 fill-yellow-500" />
                            <StarIcon className="w-5 h-5 fill-yellow-500" />
                            <StarIcon className="w-5 h-5" />
                        </div>
                        <Button>Submit</Button>
                    </div>
                </div>
            </section>
            <section className="bg-gray-100 py-12 md:py-20">
                <div className="container mx-auto px-6 md:px-10">
                    <h2 className="text-2xl md:text-3xl font-bold mb-8">Reviews</h2>
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                        <div className="bg-white rounded-lg shadow-md p-6">
                            <div className="flex items-center space-x-4 mb-4">
                                <Avatar className="w-12 h-12 border">
                                    <AvatarImage alt="Jane Doe" src="/placeholder-user.jpg" />
                                    <AvatarFallback>JD</AvatarFallback>
                                </Avatar>
                                <div>
                                    <h3 className="text-lg font-bold">Jane Doe</h3>
                                    <div className="flex items-center space-x-2 text-gray-600">
                                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                                        <span>5</span>
                                    </div>
                                </div>
                            </div>
                            <p className="text-gray-600">
                                The plumber was very professional and did an excellent job fixing my leaky faucet. I would definitely
                                use their services again.
                            </p>
                        </div>
                        <div className="bg-white rounded-lg shadow-md p-6">
                            <div className="flex items-center space-x-4 mb-4">
                                <Avatar className="w-12 h-12 border">
                                    <AvatarImage alt="John Smith" src="/placeholder-user.jpg" />
                                    <AvatarFallback>JS</AvatarFallback>
                                </Avatar>
                                <div>
                                    <h3 className="text-lg font-bold">John Smith</h3>
                                    <div className="flex items-center space-x-2 text-gray-600">
                                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                                        <span>4</span>
                                    </div>
                                </div>
                            </div>
                            <p className="text-gray-600">
                                The cleaning service was top-notch. They were thorough and left my house spotless. I highly recommend
                                them.
                            </p>
                        </div>
                        <div className="bg-white rounded-lg shadow-md p-6">
                            <div className="flex items-center space-x-4 mb-4">
                                <Avatar className="w-12 h-12 border">
                                    <AvatarImage alt="Sarah Johnson" src="/placeholder-user.jpg" />
                                    <AvatarFallback>SJ</AvatarFallback>
                                </Avatar>
                                <div>
                                    <h3 className="text-lg font-bold">Sarah Johnson</h3>
                                    <div className="flex items-center space-x-2 text-gray-600">
                                        <StarIcon className="w-5 h-5 fill-yellow-500" />
                                        <span>5</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    )
}

function GrapeIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M22 5V2l-5.89 5.89" />
            <circle cx="16.6" cy="15.89" r="3" />
            <circle cx="8.11" cy="7.4" r="3" />
            <circle cx="12.35" cy="11.65" r="3" />
            <circle cx="13.91" cy="5.85" r="3" />
            <circle cx="18.15" cy="10.09" r="3" />
            <circle cx="6.56" cy="13.2" r="3" />
            <circle cx="10.8" cy="17.44" r="3" />
            <circle cx="5" cy="19" r="3" />
        </svg>
    )
}


function HammerIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m15 12-8.373 8.373a1 1 0 1 1-3-3L12 9" />
            <path d="m18 15 4-4" />
            <path d="m21.5 11.5-1.914-1.914A2 2 0 0 1 19 8.172V7l-2.26-2.26a6 6 0 0 0-4.202-1.756L9 2.96l.92.82A6.18 6.18 0 0 1 12 8.4V10l2 2h1.172a2 2 0 0 1 1.414.586L18.5 14.5" />
        </svg>
    )
}


function PlugIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M12 22v-5" />
            <path d="M9 8V2" />
            <path d="M15 8V2" />
            <path d="M18 8v5a4 4 0 0 1-4 4h-4a4 4 0 0 1-4-4V8Z" />
        </svg>
    )
}


function SearchIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <circle cx="11" cy="11" r="8" />
            <path d="m21 21-4.3-4.3" />
        </svg>
    )
}


function StarIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
    )
}


function WashingMachineIcon(props) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M3 6h3" />
            <path d="M17 6h.01" />
            <rect width="18" height="20" x="3" y="2" rx="2" />
            <circle cx="12" cy="13" r="5" />
            <path d="M12 18a2.5 2.5 0 0 0 0-5 2.5 2.5 0 0 1 0-5" />
        </svg>
    )
}
